const express = require("express");
const admin = require("../controller/adminController");
const {adminisLoggedIn} = require("../controller/userController");
const adminRouter = express.Router();
const upload = require("../utils/adminUtil");

adminRouter.get('/home', adminisLoggedIn,admin.adminHome);
adminRouter.get('/write', admin.adminWriteG);
adminRouter.post('/write/add', upload, admin.adminWriteP);
adminRouter.get('/list/:page', admin.adminList);
adminRouter.get('/list/deleted/:page', admin.adminListDeleted);
adminRouter.get('/detail/:id', admin.adminDetail);
adminRouter.put('/detail/delete', admin.adminDelete);
adminRouter.get('/edit/:id', admin.adminPutG);
adminRouter.put('/edit', admin.adminPutP);
adminRouter.get('/search/:page(\\d+)', admin.adminSearchList);
adminRouter.get('/searchDeleted/:page(\\d+)', admin.adminSearchListD);
// adminRouter.get('/user/list', admin.adminUserList);
adminRouter.get('/user/list/:page', admin.adminUserList);
adminRouter.get('/user/detail/:id', admin.adminUserDetail);
adminRouter.get('/user/edit/:id', admin.adminUserPutG);
adminRouter.put('/user/edit', admin.adminUserPutP);
adminRouter.put('/user/quit', admin.adminUserQuit);
adminRouter.get('/user/search/:page', admin.adminUserSearchList);
adminRouter.get('/analyze', admin.adminAnalyze);
module.exports = adminRouter;